---

- hosts: localhost

    
  tasks:

    - include_vars: setup.yml
      tags: always
      
    - import_tasks: tasks/prereqs.yml
      tags: prereqs

    - import_tasks: tasks/apache.yml
      tags: apache

    - import_tasks: tasks/postgresql.yml
      tags: [pg, postgresql]

    - import_tasks: tasks/app.yml
      tags: app

      
  handlers:
    - import_tasks: handlers/main.yml
