---

- hosts: localhost

    
  tasks:

    - include_vars: setup.yml
      tags: always
      
    - include: tasks/prereqs.yml
      tags: prereqs

    - include: tasks/apache.yml
      tags: apache

    - include: tasks/postgresql.yml
      tags: [pg, postgresql]

    - include: tasks/app.yml
      tags: app

      
  handlers:
    - include: handlers/main.yml
      static: true
