---

- name: Install Apache
  apt: name={{item}}
  with_items:
    - apache2

- name: Enable Apache modules
  apache2_module: name={{item}} state=present
  with_items:
    - ssl
    - cgid
    - rewrite
  notify:
    - restart apache

- name: Push configuration
  template:
    src: apache/rma.conf.j2
    dest: /etc/apache2/conf-available/rma.conf
  notify:
    - reload apache

- name: a2enconf
  command: a2enconf rma.conf
  args:
    creates: /etc/apache2/conf-enabled/rma.conf
  notify:
    - reload apache


- name: Enable Debian default SSL vhost
  command: a2ensite default-ssl
  args:
    creates: /etc/apache2/sites-enabled/default-ssl.conf
  notify:
    - restart apache


- name: Enable redirect to https
  blockinfile:
    path: /etc/apache2/sites-available/000-default.conf
    insertafter: '^<VirtualHost'
    block: |
      {% if rma_force_https %}
      RewriteEngine On
      RewriteCond  %{REQUEST_URI}  ^/{{rma_app_name}}
      RewriteRule  .?    https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
      {% else %}
      # You should consider enforcing https for /{{rma_app_name}} here.
      {% endif %}
  notify:
    - reload apache
    
- meta: flush_handlers

