---
- name: Create installation path
  file:
    path: '{{rma_installation_path}}'
    mode: 0770
    owner: www-data
    group: www-data
    state: directory
  register: install_path

- name: Clone git repo
  git:
    repo: '{{rma_github_url}}'
    version: '{{rma_github_branch | default(omit)}}'
    dest: /tmp/{{rma_app_name}}
  register: git_clone


- name: Copy to target location
  shell: cp -rv /tmp/{{rma_app_name}}/* '{{rma_installation_path}}'
  when: git_clone.changed or install_path.changed

